config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/wps', to: 'wps#index'
  devise_for :users

  post '/areas/:id/move_to/:parent_id' => 'areas#move_to'
  post '/areas/:id/move_before/:parent_id' => 'areas#move_before'
  resources :areas
  resources :observations do
    collection { get :related }
  end
  resources :activities, only: %i[create update destroy]
  resources :setups, only: %i[create update destroy]
  resources :material_transactions, only: %i[create update destroy]
  resources :equipment
  resources :units
  resources :people
  resources :reports
  resources :materials
  resources :salus, only: %i[index show]
  resources :observation_types, only: %i[index]

  root to: 'observations#index'
end

app/models/observation.rb
# frozen_string_literal: true

require 'csv'

# The main model, an observation is a collection of activities.
class Observation < ActiveRecord::Base
  has_many :activities, dependent: :destroy
  has_many :setups, through: :activities
  has_and_belongs_to_many :areas
  has_and_belongs_to_many :observation_types
  belongs_to :person, inverse_of: :observations
  belongs_to :company, optional: true

  mount_uploader :note, NoteUploader
  mount_uploaders :notes, NoteUploader

  validates :obs_date, presence: true
  validates :observation_types, presence: true
  validates :person, presence: true
  validate :no_invalid_areas

  scope :by_company, ->(company) { where(company_id: company) }

  accepts_nested_attributes_for :activities, allow_destroy: true

  def no_invalid_areas
    errors.add(:base, 'invalid areas') if @error_areas.present?
  end

  def company_name
    company.try(:name)
  end

  def editable?(user)
    return false if user.nil?

    Set.new(user.projects).intersect?(Set.new(person.projects))
  end

  def observation_date
    obs_date
  end

  def observation_date=(date_string)
    self.obs_date = Chronic.parse(date_string)
  end

  def self.by_year(year)
    where("date_part('year',obs_date) = ?", year)
  end

  def self.by_area(areas)
    areas = areas.split(',')
    plots = areas.collect { |area| Area.find(area).expand }.flatten
    p plots
    joins(:areas).where('areas.id in (?)', plots).group(:id)
  end

  def self.by_page(page)
    ordered_by_date.includes_everything.paginate page: page
  end

  def self.includes_everything
    includes(
      { areas: %i[study treatment] },
      :observation_types,
      activities: { setups: { material_transactions: :material } }
    )
  end

  def self.ordered_by_date
    order('obs_date desc')
  end

  def areas_as_text
    @error_areas || Area.unparse(areas)
  end

  def prepopulated_area_tokens
    Area.coalese(areas).map(&:attributes).to_json
  end

  def areas_as_text=(areas_as_text)
    @error_areas = nil
    new_areas = Area.parse(areas_as_text)
    if String == new_areas.class
      @error_areas = new_areas
    else
      self.areas = new_areas
    end
  end

  def collect_from_setups(method_to_collect)
    setups.map { |setup| setup.send(method_to_collect) }.flatten.compact.uniq
  end

  def equipment_names
    setups.map(&:equipment_name).flatten.join(', ')
  end

  def in_review=(state)
    return if new_record?

    case state
    when '0'
      publish!
    when '1'
      review!
    end
  end

  def material_names
    collect_from_setups('material_names')
  end

  def materials_with_rates
    collect_from_setups('materials_with_rates').join(', ')
  end

  def n_contents
    collect_from_setups('n_contents')
  end

  def observation_type
    observation_types.first.name
  end

  def observation_type_names
    observation_types.map(&:name).join(', ')
  end

  delegate :name, to: :person, prefix: true

  def rates
    collect_from_setups('rates')
  end

  def unit_names
    collect_from_setups('unit_names')
  end
end

app/models/observation_type.rb
# A broad class of activities being done: harvesting, controlling weeds, etc.
class ObservationType < ApplicationRecord
  has_and_belongs_to_many :observations

  validates :name, uniqueness: { case_sensitive: false, message: 'must be unique' }
end

app/controllers/observations_controller.rb
# frozen_string_literal: true

# Allows modification and viewing of observations
class ObservationsController < ApplicationController
  ActionController::Parameters.action_on_unpermitted_parameters = :raise

  # helper_method :observation
  respond_to :json, :html

  # GET /observations
  # GET /observations.xml
  def index
    obstype = ObservationType.find(params[:obstype]) if params[:obstype].present?

    query = params[:query]
    if obstype
      @observations = obstype.observations
      @obstype = obstype
    elsif query
      @observations = Observation.ordered_by_date.basic_search(comment: query)
      @query = query
    else
      @observations = Observation.all
    end

    year = params[:year]
    if year.present?
      @observations = @observations.by_year(year.to_i)
      @year = year
    end

    areas = params[:areas_as_text] # TODO: what happens when you add multiple areas
    if areas.present?
      @observations = @observations.by_area(areas)
      myareas = Area.find(areas)
      @areas_as_text = [myareas].map(&:attributes).to_json
    end

    @observations = @observations.by_page(params[:page])

    respond_with @observations do |format|
      format.salus_xml { render 'index', formats: %i[salus_xml] }
      format.salus_csv { render 'index', formats: %i[salus_csv] }
    end
  end

  def show
    @observation =
      Observation.where(id: params[:id]).includes(
        :person,
        :observation_types,
        activities: [:person, { setups: [:equipment, { material_transactions: %i[material unit] }] }]
      ).first
    @areas_as_text = @observation.areas_as_text
    respond_with @observation
  end

  def new
    @observation = Observation.new
    @observation.obs_date = Time.zone.today
    respond_with @observation
  end

  def edit
    @observation =
      Observation.where(id: params[:id]).includes(:observation_types, activities: { setups: :material_transactions })
        .first
    respond_with @observation
  end

  # POST /observations
  # POST /observations.xml
  def create
    user = current_user.person
    @observation = user.observations.new(observation_params)
    @observation.company = user.default_company
    flash[:form] = @observation.save ? 'Observation was successfully created.' : 'Observation creation failed'
    flash[:error] = @observation.errors.full_messages.to_sentence
    respond_with @observation
  end

  def update
    @observation =
      Observation.where(id: params[:id]).includes(:observation_types, activities: { setups: :material_transactions })
        .first
    if @observation.update(observation_params) && @observation.save
      flash[:notice] = 'Observation was successfully updated.'
    end
    respond_with @observation
  end

  def destroy
    @observation = Observation.find(params[:id])
    @observation.destroy
    redirect_to observations_url
  end

  def related
    @observation = Observation.where(id: params[:id]).includes(areas: :observations).first
  end

  private

  def observation_params
    params.require(:observation).permit(
      :observation_date,
      :comment,
      { observation_type_ids: [] },
      :areas_as_text,
      { notes: [] },
      :notes_cache,
      activities_attributes: [
        { person: :id },
        :person_id,
        :hours,
        :id,
        :_destroy,
        {
          setups_attributes: [
            { equipment: %i[id] },
            :equipment_id,
            :id,
            :_destroy,
            {
              material_transactions_attributes: [
                :id,
                :material_id,
                { material: :id },
                :rate,
                { unit: :id },
                :unit_id,
                :_destroy
              ]
            }
          ]
        }
      ]
    )
  end
end

app/helpers/observations_helper.rb
module ObservationsHelper
  def initialize_arrays
    data = 'arrayActivityIndexes = []; arraySetupIndexes=[];'
    javascript_tag(data)
  end

  def observation_type_ids
    @observation_type_ids ||= ObservationType.all.map { |type| [type.name, type.id] }
  end

  def format_cell(array)
    array.empty? ? '_' : array.join(';;').gsub(/([,])/, ' ')
  end

  def area_help_text
    'Use TAB to enter additional areas<br />
    For example:<br />
    If you type: <b>G2R3 TAB</b><br />
    Then you will get both areas G2R3 <br />
    If you just type <b>G2 TAB</b>, you will get all of the G2 areas<br />'.html_safe
  end
end

app/views/observations/_activity.erb
<div class="activity">
  <%= form_for activity, :remote => true do |f| %>
    <%= f.hidden_field :observation_id %>
    <%= f.label :person_id, "Worker" %>
    <%= f.select :person_id, people, :include_blank => true %>
    <%= f.label :hours %>
    <%= f.text_field :hours, :Size => 5 %>
    <%= f.submit :class => 'activity_submitter' %>
  <% end %>
  <% unless activity.new_record? %>
    <dt>Setups</dt>
    <dd>
      <dl>
        <%= render :partial => 'setup', :collection => activity.setups %>
        <div>
          <input type="button" class="toggler" value="Display\Hide new setup?" />
          <div style="display: none">
            <%= render :partial => 'setup', :locals => { :setup => activity.setups.new } %>
          </div>
        </div>
      </dl>
    </dd>
    <%= link_to 'delete activity', activity_path(activity), :class => "deleter" %>
  <% end %>
</div>

app/views/observations/_flash_notice.html.erb
<% unless flash.blank? %>
  <% flash.each do |name, msg| %>
    <div class="alert alert-warning">
      <a class="close" href="#">×</a>
      <%= content_tag :p, msg %>
    <% end %>
  </div>
<% end %>

app/views/observations/_observation.html.erb
<tr>
  <td><%= observation.obs_date %></td>
  <td><%= observation.observation_type_names %></td>
  <td><%= truncate(observation.comment) %></td>
  <td><%= observation.equipment_names %></td>
  <td><%= observation.materials_with_rates %></td>
  <td>
    <%= link_to 'Show', observation_path(observation)%>
    <%= link_to 'Edit', edit_observation_path(observation) if current_user %>
  </td>
</tr>

app/views/observations/_setup.html.erb
<div class="setup">
  <%= form_for setup, :remote => true do |f| %>
    <%= f.hidden_field :activity_id %>
    <%= f.label :equipment_id, "Equipment" %>
    <%= f.select :equipment_id, equipment, :include_blank => true %>
    <%= f.submit :class => 'activity_submitter' %>
  <% end %>
  <% unless setup.new_record? %>
    <dt>Materials</dt>
    <dd>
      <dl>
        <%= render  :partial => 'material_transaction',
                    :collection => setup.material_transactions %>
        <div>
          <input type="button" class="toggler" value="Display\Hide new material?" />
          <div style="display: none">
            <%= render  :partial => 'material_transaction', :locals => { :material_transaction => setup.material_transactions.new } %>
          </div>
        </div>
      </dl>
    </dd>
    <%= link_to 'delete setup', setup_path(setup), :class => "deleter" %>
  <% end %>
</div>

app/views/observations/_unauthorized_observation.html.erb
<tr>
  <td><%= observation.obs_date %></td>
  <td><%= observation.observation_type_names %></td>
  <td><%= truncate(observation.comment) %></td>
  <td><%= observation.equipment_names %></td>
  <td><%= observation.materials_with_rates %></td>
  <td>
    <%= link_to 'Show', observation_path(observation)%>
  </td>
</tr>

app/views/observations/datafile.erb
<% @observations.each do |observation| %>
	<% observation.each_column do | column | %>
		<%= column %>
	<% end %>
<% end %>

app/views/observations/edit.html.erb
<h1>Edit observation</h1>

<div class="content">
<%= render partial: 'flash_notice' %>

Created on: <%= @observation.created_on  %>

  <div id="obsform" data-obsid="<%= @observation.id %>"></div>

<%= link_to "Show", observation_path(@observation), class: "btn btn-default" %>
<%= link_to "List Observations", observations_path, class: "btn btn-default" %>
</div>
<%= javascript_pack_tag "hello_elm" %>

app/views/observations/index.html.erb
<div>
  <%= link_to 'New observation', new_observation_path, class: "btn btn-primary" %>
</div>

<div class="row">
  <div class="col offset-md-2">
    <form>
      <div class="form-row row align-items-end">
        <div class="col">
          <input type="text" placeholder="Area" id='observation_areas_as_text' name='areas_as_text' class="token-input form-control" data-pre=<%=@areas_as_text%> >
        </div>
        <!-- <div class="col" id="area_input" data&#45;areas=<%=@areas %>></div> -->
        <div class="col">
          <input type="text" name='year' class="form-control" placeholder="Year" value=<%=@year%> >
        </div>
        <div class="col">
          <% obstype_array = options_from_collection_for_select(ObservationType.where(deprecated: false).all, :id, :name, @obstype.try(:id)) %>
          <%= select_tag(:obstype, options_for_select(obstype_array), prompt: "select an event", include_blank: true, class: 'form-control') %>
        </div>
        <div class='col'>
          <button type="submit" class="btn btn-primary">Search</button>
        </div>
      </div>
    </form>
  </div>
</div>
<div class="row">
  <div class="col">
    <div class='flickr_pagination clearfix'>
      <div class='p_16 d-flex justify-content-center'>
        <%= will_paginate @observations, :renderer => BootstrapPagination::Rails %>
      </div>
      <table class='table'>
        <tr>
          <th>Date</th>
          <th>Site</th>
          <th>Observation Type</th>
          <th>Comment</th>
          <th><%= link_to 'Areas', areas_path %></th>
          <th><%= link_to 'Material', materials_path %></th>
        </tr>

        <% @observations.each do |observation| %>
          <tr valign='top'>
            <td><%= observation.obs_date %> </td>
            <td><%= observation.company_name %></td>
            <td>
              <% observation.observation_types.each do |type| %>
                <%= type.name %>
              <% end %>
            </td>
            <td><%= truncate(observation.comment.to_s) %></td>
            <td><%= observation.areas_as_text %></td>
            <td>
              <% observation.activities.each do |activity| %>
                <% activity.setups.each do |setup| %>
                  <table>
                    <% setup.material_transactions.each do |m| %>
                      <tr>
                        <td><%= m.material.name if m %></td>
                      </tr>
                    <% end %>
                  </table>
                <% end %>
              <% end %>
            </td>
            <td><%= link_to 'Show', observation_path(observation) %></td>
            <% if signed_in? %>
              <td><%= link_to 'Edit', edit_observation_path(observation)%></td>
              <td><%= link_to 'Destroy', observation_path(observation), data: {confirm: "Are you sure?"},  method: :delete %></td>
            <% end %>
          </tr>
        <% end %>
      </table>
      <br />
      <div class='d-flex justify-content-center'>
        <%= will_paginate @observations, :renderer => BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>
<div class="row clearfix">
  <div class="col">
    <%= link_to 'New observation', new_observation_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/observations/index.salus_csv.erb
<%- headers = ["Date", "Type", "Area", "Material", "N_Content", "Rate", "Unit"] -%>
<%= CSV.generate_line headers %>
<%- @observations.each do |observation| -%>
  <%- observation.areas.each do |area| -%>
    <%- observation.observation_types.each do |type| -%>
      <%- row = [ observation.obs_date.to_s,
                  type.name,
                  area.name,
                  format_cell(observation.material_names),
                  format_cell(observation.n_contents),
                  format_cell(observation.rates),
                  format_cell(observation.unit_names) ] -%>
      <%= CSV.generate_line row %>
    <%- end -%>
  <%- end -%>
<%- end -%>

app/views/observations/new.html.erb
<h1>New Observation</h1>

<div class="content">
  <%= render partial: 'flash_notice' %>

  <div id="obsform" data-obsid=0></div>
  <%= link_to 'List Observations', observations_path %>
</div>
<%= javascript_pack_tag "hello_elm" %>

app/views/observations/related.html.erb
<h1>Related Observations</h1>

<dl>
  <% @observation.areas.each do |area| %>
    <hr />
    <dt><%= area.name %></dt>
    <dd>
      <table>
        <tr>
          <th>Date</th>
          <th>Observation Type</th>
          <th>Comment</th>
        </tr>
        <% area.observations.each do |observation| %>
          <tr valign='top'>
            <td><%= observation.obs_date %> </td>
            <td>
              <% observation.observation_types.each do |type| %>
                <%= type.name %>
              <% end %>
            </td>
            <td><%= truncate(observation.comment.to_s) %></td>
            <td><%= link_to 'Show', observation_path(observation) %></td>
            <% if signed_in? %>
              <td><%= link_to 'Edit', edit_observation_path(observation)%></td>
              <td><%= link_to 'Destroy', observation_path(observation), :confirm => 'Are you sure?', :method => :delete %></td>
            <% end %>
          </tr>
        <% end %>
      </table>
    </dd>
  <% end %>
</dl>

app/views/observations/show.html.erb
<h1>Show Observation</h1>
<p>
  <b>User:</b>
  <%= @observation.person_name %>
</p>

<p>
  <b>Created on:</b>
  <%= @observation.created_on %>
</p>
<p>
  <b>Observation Date</b>
  <%= @observation.obs_date  %>
</p>
<p>
  <b>Comment:</b><br/>
  <%= @observation.comment %>
</p>
<p>
  <b>Areas:</b><br/>
  <%= @areas_as_text %>
</p>
<p>
  <b>Observation Type:</b><br/>
  <% @observation.observation_types.each  do |type| %>
    <%= type.name %>
  <% end %>
</p>
<p>
<b>Activities: </b><br/>
<% @observation.activities.each do | activity | %>
  <div>
    Worker: <%= activity.person_name %><br/>
    <% activity.setups.each do |setup| %>
      <div class='indent'>
        Equipment: <%= setup.equipment_name %>
        <% setup.material_transactions.each do |transaction| %>
          &#149 Material: <%= transaction.material_name %>
          @ <%= transaction.rate %>
          <%= transaction.unit_name %> per acre
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>
</p>

<p>
<% unless @observation.note.file.nil? %>
  <b> Attachment:</b><br/>
  <%= link_to @observation.note.file.try(:filename), @observation.note.url %>
  </p>
<% end %>

  <b> Attachments:</b><br/>
  <ul>
<% @observation.notes.each do |note| %>
  <li><%= link_to note.file.try(:filename), note.url %></li>
<% end %>
</ul>

<%= link_to 'Related Observations', related_observations_path(id: @observation.id), class: 'btn btn-light'%>
<%= link_to 'New observation', new_observation_path, class: 'btn btn-light' %>
<%= link_to 'Edit', edit_observation_path(@observation), class: 'btn btn-light' %>
<%= link_to 'List Observations', observations_path, class: 'btn btn-light' %>