config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/wps', to: 'wps#index'
  devise_for :users

  post '/areas/:id/move_to/:parent_id' => 'areas#move_to'
  post '/areas/:id/move_before/:parent_id' => 'areas#move_before'
  resources :areas
  resources :observations do
    collection { get :related }
  end
  resources :activities, only: %i[create update destroy]
  resources :setups, only: %i[create update destroy]
  resources :material_transactions, only: %i[create update destroy]
  resources :equipment
  resources :units
  resources :people
  resources :reports
  resources :materials
  resources :salus, only: %i[index show]
  resources :observation_types, only: %i[index]

  root to: 'observations#index'
end

app/models/person.rb
# frozen_string_literal: true

# A person is both someone who performs activities, and (with an open id) a
# user of the web application.
class Person < ActiveRecord::Base
  has_many :observations, inverse_of: :person
  has_many :activities
  has_many :memberships
  has_many :companies, through: :memberships
  belongs_to :user, optional: true

  has_many :collaborations
  has_many :projects, through: :collaborations

  validates :given_name, presence: { unless: :sur_name }
  validates :sur_name, presence: { unless: :given_name }

  validate :name_must_be_unique # validates :memberships, presence: true

  scope :by_company, ->(company) { joins(:memberships).where(memberships: { company_id: company }) }

  def self.current
    where(archived: false)
  end

  def self.ordered
    order('sur_name, given_name')
  end

  def self.find_in_company(company, id)
    by_company(company).find(id)
  end

  # Default is always KBS now
  def default_company
    Company.find(1)
  end

  def name_must_be_unique
    person =
      Person.where(['lower(given_name) = ?', given_name.try(:downcase)]).where(
        ['lower(sur_name) = ?', sur_name.try(:downcase)]
      ).to_a - [self]
    errors.add(:base, 'Name must be unique') if person.present?
  end

  def name
    [given_name, sur_name].join(' ')
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

# Allows modification and viewing of people
class PeopleController < ApplicationController
  respond_to :json, :html

  # GET /people
  # GET /people.xml
  def index
    @people = params[:current] ? Person.current.ordered : Person.ordered
    respond_with @people
  end

  def show
    @person = Person.find(params[:id])
    respond_with @person
  end

  def new
    @person = Person.new
    respond_with @person
  end

  def edit
    @person = Person.find_in_company(current_user.companies, params[:id])
    respond_with @person
  end

  def create
    @person = Person.new(person_params) # into? The current user default one?
    if @person.save
      flash[:notice] = 'Person was successfully created.'
      respond_with @person
    else
      render :new
    end
  end

  def update
    @person = Person.find_in_company(current_user.companies, params[:id])
    flash[:notice] = 'Person was successfully updated.' if @person.update(person_params)
    respond_with @person
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_url
  end

  private

  def person_params
    params.require(:person).permit(:given_name, :sur_name, :companies, :archived)
  end # @person = Person.by_company(current_user.company).find(params[:id])
end

app/views/people/_form.html.erb
<%= render "shared/error_messages", :target => person %>
<%= form_for @person , html: {class: "form", role: "form" } do |form| %>
  <div class="col-sm-6">
    <div class="form-group">
      <label for='person_given_name' class="control-label">First Name</label>
      <%= form.text_field :given_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="person_sur_name" class="control-label">Last Name</label>
      <%= form.text_field :sur_name, class: "form-control" %>
    </div>
    <div  class="form-group">
      <div class="checkbox">
        <label>
          Archived (not in the dropdown box)
          <%= form.check_box :archived  %>
        </label>
      </div>
    </div>
    <%= form.submit "Submit"%>
  </div
<% end %>

app/views/people/edit.html.erb
<h1> Editing person</h1>

<%= render 'form', :person => @person %>

<%= link_to 'Show', person_path(@person) %>
|
<%= link_to 'List People', people_path %>

app/views/people/index.html.erb
<h1>People</h1>

<div>
  <% if signed_in? %>
    <%= link_to 'New person', new_person_path %>
  <% end %>
</div>

<div class='col-sm-5'>
  <table class='table'>
    <% @people.each do | person| %>
      <tr>
        <td> <%=h person.given_name %></td>
        <td> <%=h person.sur_name %><td>
            <% if signed_in? %>
              <td> <%= link_to 'Show', person_path(person) %></td>
              <td> <%= link_to 'Edit', edit_person_path(person) %></td>
              <td> <%= link_to 'Destroy', person_path(person),
                                          data: {confirm: "Are you sure you want to delete #{person.name}?"},
                                          method: :delete %></td>
            <% end %>
      </tr>
    <% end %>
  </table>
  <br/>

</div>

app/views/people/new.erb
<h1>New person</h1>

<%= render 'form', :person => @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.erb
<h1> <%=h @person.name  %> </h1>
<ul>
<% @person.activities.each do | activity | %>
  <li><%=activity.observation.obs_date %> <%= activity.observation.comment %> <%= link_to "Show", activity.observation %></li>
<% end %>
</ul>
<%= link_to 'Edit', edit_person_path(@person) if current_user  %>
<%= link_to 'Back', people_path %>