config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/wps', to: 'wps#index'
  devise_for :users

  post '/areas/:id/move_to/:parent_id' => 'areas#move_to'
  post '/areas/:id/move_before/:parent_id' => 'areas#move_before'
  resources :areas
  resources :observations do
    collection { get :related }
  end
  resources :activities, only: %i[create update destroy]
  resources :setups, only: %i[create update destroy]
  resources :material_transactions, only: %i[create update destroy]
  resources :equipment
  resources :units
  resources :people
  resources :reports
  resources :materials
  resources :salus, only: %i[index show]
  resources :observation_types, only: %i[index]

  root to: 'observations#index'
end

app/models/unit.rb
# frozen_string_literal: true

# Measurements have different units: kilograms, quarts, bushels, etc.
class Unit < ActiveRecord::Base
  has_many :material_transactions

  scope :ordered, -> { order('name') }
  validates :name, uniqueness: { case_sensitive: false }

  def si_unit_name
    return if si_unit_id.nil?

    Unit.find(si_unit_id).name
  end

  def self.si_units
    where('is_si_unit is true')
  end
end

app/controllers/units_controller.rb
# frozen_string_literal: true

# Allows modification and viewing of units
class UnitsController < ApplicationController
  respond_to :json, :html

  def index
    @units = Unit.ordered
    respond_with @units
  end

  def show
    @unit = Unit.find(params[:id])
    respond_with @unit
  end

  def new
    @unit = Unit.new
    respond_with @unit
  end

  def edit
    @unit = Unit.find(params[:id])
    respond_with @unit
  end

  def create
    @unit = Unit.new(unit_params)
    flash[:notice] = 'Unit was successfully created.' if @unit.save
    respond_with @unit
  end

  def update
    @unit = Unit.find(params[:id])
    if @unit.update(unit_params)
      flash[:notice] = 'Unit was successfully updated.'
      respond_with @unit
    else
      render :edit
    end
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy
    redirect_to units_url # respond_with @unit
  end

  private

  def unit_params
    params.require(:unit).permit(:name, :si_unit_id, :conversion_factor, :is_si_unit)
  end
end

app/views/units/_form.html.erb
<div class="form-group">
  <label>Name </label>
  <%= f.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
  <label>SI Unit</label>
  <%= f.select :si_unit_id, Unit.si_units.map {|x| [x[:name], x[:id]] }, html: {class: "form-control"}, include_blank: true %>
</div>

<div class="form-group">
  <label>Conversion Factor</label>
  <%= f.text_field :conversion_factor, class: "form-control" %>
</div>

<div class="checkbox">
  <label>
    <%= f.check_box :is_si_unit %>
    Is SI unit
  </label>
</div>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>
<div class="row col-sm-5">
<%= form_for(:unit, :url => unit_path(@unit), html: {role: "form", class: "form", method: :put}) do |f| %>

  <%= render partial: "form", locals: {f: f} %>

  <div class="form-group">
    <%= submit_tag "Update", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Show', unit_path(@unit) %> |
<%= link_to 'List', units_path %>
</div>

app/views/units/index.html.erb
<h1>Available Units</h1>

<% if signed_in? %>
  <div class="row">
    <%= link_to 'New Unit', new_unit_path %>
  </div>
<% end %>

<div class="row col-sm-8">
  <table class="table">
    <tr>
      <th>Name</th>
      <th> Conversion Factor to</th>
      <th> S.I. Unit</th>
      <% if signed_in? %>
        <th></th>
        <th></th>
        <th></th>
      <% end %>
    </tr>

    <% @units.each do |unit| %>
      <tr>
        <td><%=h unit.name %></td>
        <td> <%=h unit.conversion_factor %></td>
        <td> <%= unit.si_unit_name %></td>
        <% if signed_in? %>
          <td> <%= link_to 'Show', unit_path(unit) %></td>
          <td> <%= link_to 'Edit', edit_unit_path(unit) %></td>
          <td> <%= link_to 'Destroy', unit_path(unit), data: {confirm: "Are you sure you want to delete #{unit.name}?"},
            method: :delete %> </td>
        <% end %>
      </tr>
    <% end %>
</div>

<div class = "row col-sm-8">
  <% if signed_in? %>
    <%= link_to 'New Unit', new_unit_path %>
  <% end %>
</div>

app/views/units/new.html.erb
<h1>New Unit</h1>

<div class="row col-sm-5">
  <%= form_for(:unit, :url => units_path, html: {role: "form", class: "form" }) do |f| %>

  <%= render partial: "form", locals: {f: f} %>

  <div class="form-group">
    <%= submit_tag "Create" , class: "btn btn-primary"%>
  </div>
<% end %>
</div>

app/views/units/show.html.erb
<h1>Show Unit</h1>
<p>
	<table>
		<tr>
			<td align="right"><b>Name: &nbsp</b></td>
	 		<td align="left"><%=h @unit.name %></td>
	 	</tr>
		<tr>
	 		<td align="right"><b>SI_Unit: &nbsp</b></td>
	 		<td align="left"><%=h @unit.si_unit_id %></td>
	 	</tr>
		<tr>
	 		<td align="right"><b>Conversion Factor: &nbsp</b></td>
	 		<td align="left"><%=h @unit.conversion_factor %></td>
	 	</tr>
		<tr>
	 		<td align="right"><b>Is SI Unit: &nbsp</b></td>
	 		<td align="left"><%=h @unit.is_si_unit%></td>
	 	</tr>
	</table>
</p>

<%= link_to 'List', units_path %>