config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/wps', to: 'wps#index'
  devise_for :users

  post '/areas/:id/move_to/:parent_id' => 'areas#move_to'
  post '/areas/:id/move_before/:parent_id' => 'areas#move_before'
  resources :areas
  resources :observations do
    collection { get :related }
  end
  resources :activities, only: %i[create update destroy]
  resources :setups, only: %i[create update destroy]
  resources :material_transactions, only: %i[create update destroy]
  resources :equipment
  resources :units
  resources :people
  resources :reports
  resources :materials
  resources :salus, only: %i[index show]
  resources :observation_types, only: %i[index]

  root to: 'observations#index'
end

app/controllers/reports_controller.rb
# Allows modification and viewing of reports
class ReportsController < ApplicationController
  def index
    current = session[:current_order]
    order =
      case params[:order]
      when 'date'
        by_date_desc == current ? by_date : by_date_desc
      when 'plot'
        by_area_name_desc == current ? by_area_name : by_area_name_desc
      when 'material'
        by_material_name_desc == current ? by_material_name : by_material_name_desc
      else
        by_date
      end

    session[:current_order] = order

    @transactions =
      MaterialTransaction.includes(:observations, :areas, :material, :unit, setup: { activity: :observation })
        .find_fertilizations(order)

    respond_to(&:html)
  end

  private

  def by_date
    'obs_date, areas.name, materials.name'
  end

  def by_date_desc
    'obs_date desc, areas.name, materials.name'
  end

  def by_area_name
    'areas.name, observations.obs_date desc, materials.name'
  end

  def by_area_name_desc
    'areas.name desc, obs_date desc, materials.name'
  end

  def by_material_name
    'materials.name, obs_date desc, areas.name'
  end

  def by_material_name_desc
    'materials.name desc, obs_date desc, areas.name'
  end
end

app/views/reports/index.erb
<table border="1">
  <tr>
    <th><%= link_to 'Date', reports_path(:order => 'date') %></th>
    <th><%= link_to 'Plot', reports_path(:order => 'plot') %></th>
    <th><%= link_to 'Material', reports_path(:order => 'material') %></th>
    <th>Rate</th>
    <th>N (kg/ha)</th>
    <th>P (kg/ha)</th>
    <th>K (kg/ha)</th>
  </tr>
  <% @transactions.each do |t| %>
    <tr>
      <td><%= t.setup.activity.observation.obs_date %></td>
      <td></td>
      <td><%= t.material.name %></td>
      <td><%= "#{pluralize(t.rate,t.unit.name)} per acre" if t.unit %></td>
      <td><%= t.n_content_to_kg_ha %></td>
      <td><%= t.p_content_to_kg_ha %></td>
      <td><%= t.k_content_to_kg_ha %></td>
      <td><%= link_to "show", observation_path(t.setup.activity.observation_id) %></td>
    </tr>
  <% end %>
</table>